add context about agent failures (#712)
Summary:
Pull Request resolved: https://github.com/facebookincubator/magma/pull/712

This commit adds some context about a symphony agent unit test failure
to direct the users to whom to contact.

Reviewed By: themarwhal

Differential Revision: D17856107

fbshipit-source-id: 9fbd755ccab50545f903d8de124d4a597ffa894e

diff --git a/devmand/gateway/docker/scripts/test b/devmand/gateway/docker/scripts/test
--- a/devmand/gateway/docker/scripts/test
+++ b/devmand/gateway/docker/scripts/test
@@ -7,3 +7,11 @@ docker run \
   --sysctl net.ipv4.ping_group_range="0 0" \
   devmand-built \
   make test
+EXIT_CODE=$?
+
+if [ $EXIT_CODE -ne 0 ] ; then
+  echo "You have gotten a CI failure in devmand's unit tests."
+  echo "If you are sure your changes did not cause the issue or if you"
+  echo "need help please reach out to the south poll symphony oncall."
+  exit ${EXIT_CODE}
+fi
